### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by aqilc** [MoazSalem/colorful-notes-flutter#1]
May there be a widget to quickly glance at recent notes? This is a very important feature that when done properly, makes or breaks most notes apps.

P.S. THIS IS SUCH A GREAT NOTES APP?! HOW HAS NO ONE DISCOVERED THIS YET WHAT. Your work is great and the app looks stunning! Once again, please keep up the great work and I sincerely hope it blows up soon!

**Comment by MoazSalem** [comment]
I appreciate the feedback, I'm genuinely happy when someone compliments my work.

I am unsure if I can add home screen widgets as it's not fully supported by Flutter and will require more native code, but sure it's interesting I will look into it.

**Comment by MoazSalem** [comment]
The feature has been added!!, it was a little hard with no knowledge of kotlin as I said, but it's almost fully working, and you can cycle between notes by pressing on the widget.

two notable problems would be that the widgets would look different depending on the Android version, below android 12 will look square, but above it will have rounded corners. 

the second is that any two instances of the same size of the widget (I added 4 sizes) will have the same index hence the same note, I tried working on this but failed, might give it another look later.

 here is how it looks on Android 13 :

<img src="https://github.com/MoazSalem/Colorful_Notes/assets/88838071/d9bb4cc3-6a59-46d3-88fa-fbbeda7d6dea" width="300"> 
<br><br>
if you find any other issues please tell me.

**Comment by aqilc** [comment]
Thank you so much for working on it, that looks really handy! I'm fine with rounded corners either way so don't worry about it too much. I haven't gotten the chance to test it as I have been busy, but I will update you soon. I have got to say that the voice notes feature is super unique and it's been a good experience so far. The UI design for everything is also cohesive and generally really good so far, I'd say a corporation made this app, not a lone developer trying Flutter for the first time.

**Comment by MoazSalem** [comment]
Widgets have been added to the app
